#!/usr/bin/env bash

set -e

install-hashicorp-app () {
    name=$1
    url=$2

    if ! [ -x "$(command -v ${name})" ]; then
        wkDir=/tmp/install-${name}
        mkdir -p ${wkDir}
        cd ${wkDir}
        curl ${url} > ${name}.zip
        unzip -o ${name}.zip
        mv ${name} /usr/local/bin/${name}
    fi
}


consulDataDir="/tmp/consul"

case "$1" in
    install-vault)
        if [[ -n $2 ]]; then
            url="https://releases.hashicorp.com/vault/${2}/vault_${2}_linux_amd64.zip"
        else
            echo "Need a version"
            exit 1
        fi

        install-hashicorp-app vault ${url}
    ;;
    install-consul)
        url="https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_linux_amd64.zip"

        install-hashicorp-app consul ${url}
    ;;

    start-consul)
        consul agent -server -data-dir=${consulDataDir} -bootstrap-expect $2 &
    ;;

    stop-consul)
        rm -r ${consulDataDir}
    ;;


esac